title: Scribd Technology
email: talent@scribd.com
description: >- # this means to ignore newlines until "baseurl:"
  Scribd technology builds and delivers one of the world's largest libraries,
  bringing the best books, audiobooks, and journalism to millions of people
  around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.scribd.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'UA-443684-30'
# Replace this with a tag for the series of blog posts to be featured on the homepage
featured_series: 'di-series'

# GitHub Metadata
# Used for "improve this page" link
branch: master

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

twitter_username: scribdtech
facebook_username: scribd
linkedin_username: scribd
github_username:  scribd

# Assets
sass:
    sass_dir: assets/_sass

# Blog settings
permalink: "/blog/:year/:title:output_ext"
date_format: "%B %-d, %Y"
paginate: 12
paginate_path: "/blog/page:num/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
